### ISSUE TITLE
Bus error (core dumped) for mips_24kc

### ISSUE THREAD

**Issue by BKPepe** [openwrt/docker#185]
While testing via Docker container for mips_24kc, many PRs are failing due to bus error (core dumped)

```
Run docker run --platform linux/mips_24kc --rm -v $GITHUB_WORKSPACE:/ci \
 [https://downloads.openwrt.org/snapshots/targets/malta/be/packages/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/packages.adb]
 [https://downloads.openwrt.org/snapshots/targets/malta/be/kmods/6.12.49-1-1004e46bb6d109efd906bef863ce119d/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/mips_24kc/luci/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/mips_24kc/packages/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/mips_24kc/routing/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/mips_24kc/telephony/packages.adb]
 [https://downloads.openwrt.org/snapshots/packages/mips_24kc/video/packages.adb]
 [/ci/packages.adb]
OK: 10356 distinct packages available

Testing package attendedsysupgrade-common in version 9 from utils/attendedsysupgrade-common
No test.sh script available

Testing package bmon in version 4.0 from net/bmon
No test.sh script available

Testing package confuse in version 3.3 from libs/confuse
No test.sh script available

Testing package vim in version 9.1 from utils/vim
No pre-test.sh script available
(1/3) Installing terminfo (6.4-r3)
terminfo-6.4-r3.post-install: Executing script...
(2/3) Installing libncurses6 (6.4-r3)
Bus error (core dumped)
Error: Process completed with exit code 138.
```

**Comment by tofurky** [comment]
`libncurses6` was one of the packages giving me grief on kirkwood per https://github.com/openwrt/openwrt/issues/21241 when installing via apk, which was traced to the unaligned access and should now be resolved.

I am curious if those changes resolve the issue here as well.

It seems that `docker run --platform` here is just using e.g. `qemu-mips` and not a full kernel (i.e. `qemu-system-mips`) so the automatic kernel fixup per `/sys/kernel/debug/mips/unaligned_action` wouldn't happen.

I can repro a SIGBUS in qemu-system-mips via the 25.12 malta initramfs when doing `apk add libncurses6` after doing `echo 1 > /sys/kernel/debug/mips/unaligned_action` to raise a signal rather than letting the kernel silently fix things.

**Comment by robimarko** [comment]
I guess we can reenable mips_24kc tests, they could well be fixed when unaligned was fixed

**Comment by tofurky** [comment]
I reenabled `ath79` on my fork of actions-shared-workflows then tested the actions via a no-op PR to `vim`; succeeds now: https://github.com/tofurky/packages/actions/runs/22078075486/job/63797978595?pr=6

```
...
Testing package vim in version 9.2.0 from utils/vim
No pre-test.sh script available
(1/3) Installing terminfo (6.4-r3)
  Executing terminfo-6.4-r3.post-install
(2/3) Installing libncurses6 (6.4-r3)
  Executing libncurses6-6.4-r3.post-install
(3/3) Installing vim (9.2.0-r2)
  Executing vim-9.2.0-r2.post-install
OK: 15.0 MiB in 124 packages
Use package specific test.sh
...
```

**Comment by tofurky** [comment]
Per https://github.com/openwrt/actions-shared-workflows/commit/bc7ea47338e8538aac9dd9e3fd99b4d3d2469be5 it looks good so far in "Test via Docker container":

https://github.com/openwrt/packages/actions/runs/22189035850/job/64182280019
https://github.com/openwrt/packages/actions/runs/22122770590/job/63957665290

**Comment by robimarko** [comment]
It would have shown up already if still broken.

So, I think we can close this for now.

**Comment by BKPepe** [comment]
For reference, it was enabled in https://github.com/openwrt/actions-shared-workflows/commit/bc7ea47338e8538aac9dd9e3fd99b4d3d2469be5

**Comment by robimarko** [comment]
Yes
